services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/TodoApp
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jithin
      POSTGRES_DB: ToDoApplicationDatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
